blank_issues_enabled: false
contact_links:
  - name: GitHub.com Enterprise POC
    url: https://github.com/jerick1976/game
    about: POC for making comparisons between GE, GHE and AWS based solutions.
